- install-rm-plugin:
    name=redmine_xls_export
    ver=0.2.1.t4
    url=https://github.com/two-pack/redmine_xls_export.git
  environment: env

- install-rm-plugin:
    name=redmine_plugin_views_revisions
    ver=redmine_plugin_views_revisions
    url=http://www.redmine.org/attachments/download/7705/redmine_plugin_views_revisions_v001.zip
  environment: env

- install-rm-plugin:
    name=redmine_importer
    ver=master
    url=https://github.com/zh/redmine_importer.git
  environment: env

- install-rm-plugin:
    name=redmine_code_review
    ver=default
    url=https://bitbucket.org/haru_iida/redmine_code_review
  environment: env

- install-rm-plugin:
    name=redmine_hudson
    ver=redmine2.x
    url=https://bitbucket.org/okamototk/redmine_hudson
  environment: env

- install-rm-plugin:
    name=redmine_backlogs
    ver=master
    url=https://github.com/backlogs/redmine_backlogs.git
  environment: env

- install-rm-plugin:
    name=redmine_spent_time_column
    ver=backlogs-support
    url=https://github.com/mikoto20000/redmine_spent_time_column.git
  environment: env

- install-rm-plugin:
    name=redmine_scm
    ver=redmine-2.1.x
    url=https://github.com/alminium/redmine_scm.git
  environment: env
- copy: src=files/scm.yml dest=/opt/alminium/config
- copy: src=files/alm-scm-post-create dest=/opt/alminium/bin
- copy: src=files/alm-sync-scm dest=/opt/alminium/bin
- copy: src=files/hooks dest=/opt/alminium

- install-rm-plugin:
    name=redmine_drafts
    ver=alm
    url=https://github.com/alminium/redmine_drafts.git
  environment: env

- install-rm-plugin:
    name=clipboard_image_paste
    ver=master
    url=https://github.com/peclik/clipboard_image_paste.git
  environment: env

- install-rm-plugin:
    name=redmine_banner
    ver=master
    url=https://github.com/akiko-pusu/redmine_banner.git
  environment: env

- install-rm-plugin:
    name=open_flash_chart
    ver=master
    url=https://github.com/pullmonkey/open_flash_chart.git
  environment: env

- install-rm-plugin:
    name=redmine_charts
    ver=develop
    url=https://github.com/drakontia/redmine_charts.git
  environment: env

- install-rm-plugin:
    name=redmine_local_avatars
    ver=master
    url=https://github.com/luckval/redmine_local_avatars.git
  environment: env

- install-rm-plugin:
    name=redmine_git_branch_hook
    ver=master
    url=https://github.com/mikoto20000/redmine_git_branch_hook.git
  environment: env

