- name: Remove ruby-libs
  yum: name=ruby-libs state=absent

- name: Setup Additional repository
  yum: name=epel-release
  with_items:
  - epel-release
  - centos-release-scl

- name: Install Ruby
  yum: name={{ item }}
  with_items:
  - rh-ruby23-ruby
  - rh-ruby23-ruby-devel

- name: Install RPMs
  yum: name={{ item }} state=installed
  with_items:
  - deltarpm
  - libyaml
  - firewalld
  - unzip
  - ImageMagick
  - httpd
  - mod_ssl
  - sudo
  - gcc-c++
  - patch
  - git
  - subversion
  - mercurial
  - mod_wsgi
  - mod_perl
  - perl-Digest-SHA
  - libical
  - python-docutils
  - wget
  - libselinux-python
  - make
  - gcc
  - which
  - openssl-devel
  - curl-devel
  - zlib-devel
  - ImageMagick-devel
  - libxml2-devel
  - libxslt-devel
  - sqlite-devel
  - libffi-devel
  - httpd-devel
  - apr-devel 

- name: Create module directory for Redmine authentication
  file: path=/etc/httpd/Apache/Authn state=directory owner=apache group=apache

- debug: msg="============= Setup Passenger ====================="
#- name: Install Passenger
#  get_url: url=https://oss-binaries.phusionpassenger.com/yum/definitions/el-passenger.repo dest=/etc/yum.repos.d/passenger.repo validate_certs=no
#  environment: "{{env}}"

#- name: Disable gpg check for passenger repository
#  lineinfile: dest=/etc/yum.repos.d/passenger.repo state=present regexp=^repo_gpgcheck=1 line=repo_gpgcheck=0
#- name: Disable gpg check for passenger source repository
# lineinfile: dest=/etc/yum.repos.d/passenger.repo state=present regexp=^repo_gpgcheck=1 line=repo_gpgcheck=0

#- name: Install passenger's gpg key
#  rpm_key: state=present key=https://packagecloud.io/gpg.key validate_certs=no
#  environment: "{{env}}"

#- name: Install passenger
#  yum: name=mod_passenger disable_gpg_check=yes

- name: Install Passenger
  command: scl enable rh-ruby23 "gem install passenger --no-rdoc --no-ri"
  environment: "{{env}}"

- name: Build mod_passenger
  command: scl enable rh-ruby23 "passenger-install-apache2-module --auto"

- name: Install Passenger Config
  shell: scl enable rh-ruby23 "passenger-install-apache2-module --no-compile --snippet > /etc/httpd/conf.modules.d/00-passenger.conf"

- debug: msg="============= Setup Redmine ====================="

- name: Checkout Redmine Source Code
  git: repo=https://github.com/redmine/redmine.git version={{redmine_ver}} dest=/opt/alminium
  environment: "{{env}}"

- name: Create Redmine Database Configuration
  template: src=database.yml.j2 dest=/opt/alminium/config/database.yml owner=apache group=apache

- name: Run Redmine Install Script
  script: install-redmine.sh /opt/alminium {{LANG}}
  environment: "{{env}}"

- name: Create Apache Configuration
  template: src=redmine.conf.j2 dest=/etc/httpd/conf.d/redmine.conf owner=apache group=apache

- name: Create bin directory for ALMinium
  file: path=/opt/alminium/bin state=directory owner=apache group=apache recurse=true

- name: Copy repository sync script
  copy: src=alm-sync-scm dest=/opt/alminium/bin

- name: Create temp directory
  file: path=/opt/alminium/tmp state=directory owner=apache group=apache mode=777

- name: Copy database initialize script
  copy: src=init.mysql dest=/tmp

- name: Initialize Database
  command: mysql -u {{dbuser}} --password={{dbpasswd}} -h {{groups['database'][0]}} {{dbname}} -e "source /tmp/init.mysql"

- name: Disable SELinux
  selinux: state=disabled

- block: # Not Docker
  - name: Start httpd service
    service: name=httpd state=restarted enabled=yes

# TODO: iptables should enabled
#- service: name=iptables state=stopped enabled=no
#  when: docker is undefined
  - service: name=firewalld state=stopped enabled=no

  when: (ansible_virtualization_type is undefined) or
        (ansible_virtualization_type != "docker")

- block: # For Docker

  - name: Docker
    yum: name=python-pip

  - pip: name=supervisor

  - copy: src=supervisord.conf dest=/etc/supervisord.conf

  - command: /usr/bin/supervisord -c /etc/supervisord.conf
    async: 15
    poll: 0

  when: (ansible_virtualization_type is defined) and
        (ansible_virtualization_type == "docker")

- name: Create Test Project
  command: >
    curl --user admin:admin -L -k
         -H "Content-Type: application/json"
         -d '{"project": {"name": "test", "identifier": "test", "is_public": "true", "tracker_ids": [1,2,3]}}'
         https://127.0.0.1/projects.json
#  failed_when: "error in command_result.stdout"
  register: result
  until: result.rc == 9
  retries: 3
  delay: 15
  ignore_errors: yes
  tags:
   - no_reinit

- name: Add admin as test project member
  command: >
    curl --user admin:admin -L -k
         -H "Content-Type: application/json"
         -d '{"membership": {"user_id": "1", "role_ids": [3]}}'
         https://127.0.0.1/projects/test/memberships.json
#  failed_when: "error in command_result.stdout"
  ignore_errors: yes
  tags:
   - no_reinit
